# Generated by Django 3.0.6 on 2020-05-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_big', models.CharField(max_length=255)),
                ('cate_small', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sigun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_nm', models.CharField(max_length=255)),
                ('sigun_nm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpnm_nm', models.CharField(max_length=255)),
                ('refine_roadnm_addr', models.CharField(max_length=255)),
                ('refine_lotno_addr', models.CharField(max_length=255)),
                ('telno', models.CharField(max_length=255, null=True)),
                ('region_mny_nm', models.CharField(max_length=255, null=True)),
                ('brnhstrm_mny_use_posbl_yn', models.CharField(max_length=255, null=True)),
                ('card_mny_use_posbl_yn', models.CharField(max_length=255, null=True)),
                ('mobile_mny_use_posbl_yn', models.CharField(max_length=255, null=True)),
                ('refine_zip_cd', models.CharField(max_length=255, null=True)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='makedb.Category')),
                ('sigun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='makedb.Sigun')),
            ],
        ),
    ]
